version: "3.8"

networks:
  localnet:
    name: localnet
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
    - localnet