server:
  port: ${PORT:8081}

spring:
  application:
    name: service-book-read-side
  datasource:
    url: jdbc:h2:file:/tmp/data/H2/dbread
    username: sa
    password: 
  h2:
    console:
        enabled: true
  sql:
      init:
          mode: always